ComputerShop/ComputerShop-war/src/java/com/group/controller/OrdersEntityController.java
package com.group.controller;

import com.group.entity.OrdersEntity;
import com.group.controller.util.JsfUtil;
import com.group.controller.util.PaginationHelper;
import com.group.entity.CustomersEntity;
import com.group.entity.DistrictsEntity;
import com.group.entity.ProvincesEntity;
import com.group.session.CustomersEntityFacade;
import com.group.session.DistrictsEntityFacade;
import com.group.session.OrdersEntityFacade;
import com.group.session.ProvincesEntityFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "ordersEntityController")
@SessionScoped
public class OrdersEntityController implements Serializable {

    private OrdersEntity current;
    private DataModel items = null;
    @EJB
    private com.group.session.OrdersEntityFacade ejbFacade;
    @EJB
    private com.group.session.ProvincesEntityFacade provinceFacade;
    @EJB
    private com.group.session.DistrictsEntityFacade districtFace;
    @EJB
    private com.group.session.CustomersEntityFacade customerFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    
    private List<ProvincesEntity> listProvince;
    private List<DistrictsEntity> listDistrict;
    private List<CustomersEntity> listCustomer;
    private List<CustomersEntity> listSearch;
    private ArrayList<SelectItem> temp3;
    
    private String name;
    
    public OrdersEntityController() {
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public ProvincesEntityFacade getProvinceFacade() {
        return provinceFacade;
    }

    public DistrictsEntityFacade getDistrictFacade() {
        return districtFace;
    }
    
    public CustomersEntityFacade getCustomerFacade(){
        return customerFacade;
    }
    
    public String searchResult(){
        ArrayList<OrdersEntity> temp=new ArrayList<>();
        listSearch= getCustomerFacade().findByName(name);
        for (int i=0;i<listSearch.size();i++) {
            Collection<OrdersEntity> itemOrder=listSearch.get(i).getOrdersEntityCollection();
            if(itemOrder!=null){
                for(OrdersEntity item:itemOrder)
                    temp.add(item);
            }
        }
        items=new ListDataModel(temp);
        return "managerorder";
    }
    
    public ArrayList getReturnProvince() {
        ArrayList<SelectItem> temp = new ArrayList<>();
        listProvince = getProvinceFacade().findAll();
        for (ProvincesEntity item : listProvince) {
            temp.add(new SelectItem(item, item.getProvinceName()));
        }
        return temp;
    }

    public ArrayList getReturnDistrict() {
        ArrayList<SelectItem> temp2 = new ArrayList<>();
        temp2 = temp3;
        /*listDistrict = getDistrictFacade().findAll();
         for (DistrictsEntity item2 : listDistrict) {
         temp2.add(new SelectItem(item2, item2.getDistrictName()));
         }*/
        return temp2;
    }

    public ArrayList loadDistrictBasedProvince() {
        temp3 = new ArrayList<>();
        listDistrict = getDistrictFacade().findAll();
        for (DistrictsEntity item3 : listDistrict) {
            if (item3.getProvinceId().equals(current.getProvinceId())) {
                temp3.add(new SelectItem(item3, item3.getDistrictName()));
            }
        }
        return temp3;
    }
    
    public ArrayList getReturnCustomer(){
        ArrayList<SelectItem> tempcus=new ArrayList<>();
        listCustomer= getCustomerFacade().findAll();
        for (CustomersEntity itemcus : listCustomer) {
            tempcus.add(new SelectItem(itemcus, itemcus.getLastName()+" "+itemcus.getFirstName()));
        }
        return tempcus;
    }
    
    public OrdersEntity getSelected() {
        if (current == null) {
            current = new OrdersEntity();
            selectedItemIndex = -1;
        }
        return current;
    }

    private OrdersEntityFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "managerorder";
    }

    public String prepareView() {
        current = (OrdersEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new OrdersEntity();
        selectedItemIndex = -1;
        return "addNewOrder";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrdersEntityCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (OrdersEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "editorder";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrdersEntityUpdated"));
            return "managerorder";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (OrdersEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "managerorder";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrdersEntityDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "managerorder";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "managerorder";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = OrdersEntity.class)
    public static class OrdersEntityControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            OrdersEntityController controller = (OrdersEntityController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "ordersEntityController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override

ComputerShop/ComputerShop-war/src/java/com/group/controller/RolesEntityController.java
package com.group.controller;

import com.group.entity.RolesEntity;
import com.group.controller.util.JsfUtil;
import com.group.controller.util.PaginationHelper;
import com.group.session.RolesEntityFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "rolesEntityController")
@SessionScoped
public class RolesEntityController implements Serializable {

    private RolesEntity current;
    private DataModel items = null;
    @EJB
    private com.group.session.RolesEntityFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    
    private String roleName;
    private List<RolesEntity> listRole;

    public RolesEntityController() {
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
    public String returnSearch(){
        listRole=getFacade().findByName(roleName);
        items=new ListDataModel(listRole);
        return "managerrole";
    }
    
    public RolesEntity getSelected() {
        if (current == null) {
            current = new RolesEntity();
            selectedItemIndex = -1;
        }
        return current;
    }

    private RolesEntityFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (RolesEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new RolesEntity();
        selectedItemIndex = -1;
        return "addrole";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RolesEntityCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (RolesEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "editrole";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RolesEntityUpdated"));
            return "managerrole";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (RolesEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "managerrole";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RolesEntityDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "managerrole";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "managerrole";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = RolesEntity.class)
    public static class RolesEntityControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            RolesEntityController controller = (RolesEntityController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "rolesEntityController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof RolesEntity) {
                RolesEntity o = (RolesEntity) object;
                return getStringKey(o.getRoleId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + RolesEntity.class.getName());
            }
        }

    }

}

ComputerShop/ComputerShop-war/web/adminstrator/managerorder/editorder.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../../template/_layoutadminstrator.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="content">
        <h:form>
            <ui:include src="form_order.xhtml"/>
            <div class="action">
                <h:commandButton action="#{ordersEntityController.update()}" value="Update Order"/>
            </div>
        </h:form>
    </ui:define>
</ui:composition>

ComputerShop/ComputerShop-war/web/adminstrator/managerorder/form_order.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <div class="form-product">
        <table>
            <tr>
                <td>
                    <h:outputLabel value="#{bundle.ViewOrdersEntityLabel_amount}" for="amount"/>
                    <h:inputText a:placeholder="Amount" value="#{ordersEntityController.selected.amount}" id="amount" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_amount}"/>
                    <span>*<h:message for="amount"/></span>
                </td>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_orderDate}" for="orderdate"/>
                    <h:inputText a:placeholder="Order Date" value="#{ordersEntityController.selected.orderDate}" class="datepicker" id="orderdate" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_orderDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy"/>
                    </h:inputText>
                    <span>*<h:message for="orderdate"/></span>
                </td>
            </tr>
            <tr>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_orderShippingStatus}" for="ordershippingstatus"/>
                    <h:selectOneMenu value="#{ordersEntityController.selected.orderShippingStatus}">
                        <f:selectItem itemValue='0' itemLabel="Dang Xu Ly Don Hang"/>
                        <f:selectItem itemValue='1' itemLabel="Ket Thuc Don Hang"/>
                    </h:selectOneMenu>
                </td>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_paymentType}" for="paymenttype"/>
                    <h:inputText a:placeholder="Payment Type" value="#{ordersEntityController.selected.paymentType}" id="paymenttype" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_paymentType}"/>
                    <span>*<h:message for="paymenttype"/></span>
                </td>
            </tr>
            <tr>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_currencyCode}" for="currencyCode" />
                    <h:inputText a:placeholder="Currency Code" value="#{ordersEntityController.selected.currencyCode}" id="curencyCode" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_currencyCode}"/>
                    <span>*<h:message for="currencyCode"/></span>
                </td>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_shippingStreet}" for="shippingStreet" />
                    <h:inputText a:placeholder="Shipping Street" value="#{ordersEntityController.selected.shippingStreet}" id="shippingStreet" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_shippingStreet}"/>
                    <span>*<h:message for="shippingStreet"/></span>
                </td>
            </tr>
            <tr>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_shippingProvince}" for="shippingProvince" />
                    <h:selectOneMenu value="#{ordersEntityController.selected.provinceId}" id="shippingProvince" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_shippingProvince}">
                        <f:selectItem itemValue="#{null}" itemLabel="--Chon Tinh/Thanh Pho--"/>
                        <f:selectItems value="#{ordersEntityController.returnProvince}"/>
                        <f:ajax event="change" render="shippingDistrict" listener="#{ordersEntityController.loadDistrictBasedProvince()}"/>
                    </h:selectOneMenu>
                </td>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_shippingDistrict}" for="shippingDistrict" />

                    <h:selectOneMenu value="#{ordersEntityController.selected.districtId}" id="shippingDistrict" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_shippingDistrict}">
                        <f:selectItem value="#{null}" itemLabel="--Chon Quan/Huyen--"/>
                        <f:selectItems value="#{ordersEntityController.returnDistrict}"/>
                    </h:selectOneMenu>
                </td>
            </tr>
            <tr>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_shippingCountry}" for="shippingCountry" />
                    <h:selectOneMenu value="#{ordersEntityController.selected.shippingCountry}" id="shippingCountry" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_shippingCountry}">
                        <f:selectItem itemValue="VN" itemLabel="Viet Nam"/>
                        <f:selectItem itemValue="LAO" itemLabel="Lao"/>
                    </h:selectOneMenu>
                    <span>*<h:message for="shippingCountry"/></span>
                </td>
                <td>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_phoneNumber}" for="phoneNumber" />
                    <h:inputText a:placeholder="Phone Number" value="#{ordersEntityController.selected.phoneNumber}" id="phoneNumber" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_phoneNumber}"/>
                    <span>*<h:message for="phoneNumber"/></span>
                </td>
            </tr>
            <tr>
                <td>
                    <h:outputLabel value="Customer Name" for="customerid"/>
                    <h:selectOneMenu id="customerid" value="#{ordersEntityController.selected.customerId}" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_customerId}">
                        <f:selectItems value="#{ordersEntityController.returnCustomer}"/>
                    </h:selectOneMenu>
                    <span>*<h:message for="customerid"/></span>
                </td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <h:messages class="messagesucsess"/>
    </div>
</ui:composition>