ComputerShop/ComputerShop-war/src/java/com/group/controller/DistrictsEntityController.java
package com.group.controller;

import com.group.entity.DistrictsEntity;
import com.group.controller.util.JsfUtil;
import com.group.controller.util.PaginationHelper;
import com.group.entity.ProvincesEntity;
import com.group.session.DistrictsEntityFacade;
import com.group.session.ProvincesEntityFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "districtsEntityController")
@SessionScoped
public class DistrictsEntityController implements Serializable {

    private DistrictsEntity current;
    private DataModel items = null;
    @EJB
    private com.group.session.DistrictsEntityFacade ejbFacade;
    @EJB
    private com.group.session.ProvincesEntityFacade provinceFacde;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    
    private List<ProvincesEntity> listProvince;
    private String districtName;
    private List<DistrictsEntity> listDistrict;

    public DistrictsEntityController() {
    }

    public String returnSearch(){
        listDistrict=getFacade().findByName(districtName);
        items=new ListDataModel(listDistrict);
        return "managerdistrict";
    }
    
    public ArrayList getReturnProvince(){
        ArrayList temp=new ArrayList();
        listProvince=getProvinceFace().findAll();
        for (ProvincesEntity item : listProvince) {
            temp.add(new SelectItem(item, item.getProvinceName()));
        }
        return temp;
    }

    public String getDistrictName() {
        return districtName;
    }

    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }
    
    public DistrictsEntity getSelected() {
        if (current == null) {
            current = new DistrictsEntity();
            selectedItemIndex = -1;
        }
        return current;
    }

    private DistrictsEntityFacade getFacade() {
        return ejbFacade;
    }

    private ProvincesEntityFacade getProvinceFace(){
        return provinceFacde;
    }
    
    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (DistrictsEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new DistrictsEntity();
        selectedItemIndex = -1;
        return "adddistrict";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DistrictsEntityCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (DistrictsEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "editdistrict";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DistrictsEntityUpdated"));
            return "managerdistrict";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (DistrictsEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "managerdistrict";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DistrictsEntityDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "managerdistrict";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "managerdistrict";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = DistrictsEntity.class)
    public static class DistrictsEntityControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            DistrictsEntityController controller = (DistrictsEntityController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "districtsEntityController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof DistrictsEntity) {
                DistrictsEntity o = (DistrictsEntity) object;
                return getStringKey(o.getDistrictId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + DistrictsEntity.class.getName());
            }
        }

    }

}

ComputerShop/ComputerShop-war/web/pagetemplate/districtsEntity/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateDistrictsEntityTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateDistrictsEntityLabel_districtId}" for="districtId" />
                    <h:inputText id="districtId" value="#{districtsEntityController.selected.districtId}" title="#{bundle.CreateDistrictsEntityTitle_districtId}" required="true" requiredMessage="#{bundle.CreateDistrictsEntityRequiredMessage_districtId}"/>
                    <h:outputLabel value="#{bundle.CreateDistrictsEntityLabel_districtName}" for="districtName" />
                    <h:inputText id="districtName" value="#{districtsEntityController.selected.districtName}" title="#{bundle.CreateDistrictsEntityTitle_districtName}" required="true" requiredMessage="#{bundle.CreateDistrictsEntityRequiredMessage_districtName}"/>
                    <h:outputLabel value="#{bundle.CreateDistrictsEntityLabel_provinceId}" for="provinceId" />
                    <h:selectOneMenu id="provinceId" value="#{districtsEntityController.selected.provinceId}" title="#{bundle.CreateDistrictsEntityTitle_provinceId}" required="true" requiredMessage="#{bundle.CreateDistrictsEntityRequiredMessage_provinceId}">
                        <f:selectItems value="#{provincesEntityController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{districtsEntityController.create}" value="#{bundle.CreateDistrictsEntitySaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{districtsEntityController.prepareList}" value="#{bundle.CreateDistrictsEntityShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateDistrictsEntityIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

ComputerShop/ComputerShop-war/web/pagetemplate/districtsEntity/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditDistrictsEntityTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditDistrictsEntityLabel_districtId}" for="districtId" />
                    <h:inputText id="districtId" value="#{districtsEntityController.selected.districtId}" title="#{bundle.EditDistrictsEntityTitle_districtId}" required="true" requiredMessage="#{bundle.EditDistrictsEntityRequiredMessage_districtId}"/>
                    <h:outputLabel value="#{bundle.EditDistrictsEntityLabel_districtName}" for="districtName" />
                    <h:inputText id="districtName" value="#{districtsEntityController.selected.districtName}" title="#{bundle.EditDistrictsEntityTitle_districtName}" required="true" requiredMessage="#{bundle.EditDistrictsEntityRequiredMessage_districtName}"/>
                    <h:outputLabel value="#{bundle.EditDistrictsEntityLabel_provinceId}" for="provinceId" />
                    <h:selectOneMenu id="provinceId" value="#{districtsEntityController.selected.provinceId}" title="#{bundle.EditDistrictsEntityTitle_provinceId}" required="true" requiredMessage="#{bundle.EditDistrictsEntityRequiredMessage_provinceId}">
                        <f:selectItems value="#{provincesEntityController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{districtsEntityController.update}" value="#{bundle.EditDistrictsEntitySaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditDistrictsEntityViewLink}"/>
                <br />
                <h:commandLink action="#{districtsEntityController.prepareList}" value="#{bundle.EditDistrictsEntityShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditDistrictsEntityIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

ComputerShop/ComputerShop-war/web/pagetemplate/districtsEntity/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListDistrictsEntityTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListDistrictsEntityEmpty}" rendered="#{districtsEntityController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{districtsEntityController.items.rowCount > 0}">
                    <h:outputText value="#{districtsEntityController.pagination.pageFirstItem + 1}..#{districtsEntityController.pagination.pageLastItem + 1}/#{districtsEntityController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{districtsEntityController.previous}" value="#{bundle.Previous} #{districtsEntityController.pagination.pageSize}" rendered="#{districtsEntityController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{districtsEntityController.next}" value="#{bundle.Next} #{districtsEntityController.pagination.pageSize}" rendered="#{districtsEntityController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{districtsEntityController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDistrictsEntityTitle_districtId}"/>
                            </f:facet>
                            <h:outputText value="#{item.districtId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDistrictsEntityTitle_districtName}"/>
                            </f:facet>
                            <h:outputText value="#{item.districtName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDistrictsEntityTitle_provinceId}"/>
                            </f:facet>
                            <h:outputText value="#{item.provinceId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{districtsEntityController.prepareView}" value="#{bundle.ListDistrictsEntityViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{districtsEntityController.prepareEdit}" value="#{bundle.ListDistrictsEntityEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{districtsEntityController.destroy}" value="#{bundle.ListDistrictsEntityDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{districtsEntityController.prepareCreate}" value="#{bundle.ListDistrictsEntityCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListDistrictsEntityIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

ComputerShop/ComputerShop-war/web/pagetemplate/districtsEntity/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewDistrictsEntityTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewDistrictsEntityLabel_districtId}"/>
                    <h:outputText value="#{districtsEntityController.selected.districtId}" title="#{bundle.ViewDistrictsEntityTitle_districtId}"/>
                    <h:outputText value="#{bundle.ViewDistrictsEntityLabel_districtName}"/>
                    <h:outputText value="#{districtsEntityController.selected.districtName}" title="#{bundle.ViewDistrictsEntityTitle_districtName}"/>
                    <h:outputText value="#{bundle.ViewDistrictsEntityLabel_provinceId}"/>
                    <h:outputText value="#{districtsEntityController.selected.provinceId}" title="#{bundle.ViewDistrictsEntityTitle_provinceId}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{districtsEntityController.destroyAndView}" value="#{bundle.ViewDistrictsEntityDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewDistrictsEntityEditLink}"/>
                <br />
                <h:commandLink action="#{districtsEntityController.prepareCreate}" value="#{bundle.ViewDistrictsEntityCreateLink}" />
                <br />
                <h:commandLink action="#{districtsEntityController.prepareList}" value="#{bundle.ViewDistrictsEntityShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewDistrictsEntityIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>